### ISSUE TITLE
Unable to log into my account

### ISSUE THREAD

**Issue by titis14** [cyr-ius/hass-audiconnect#67]
**Describe the bug**
Hi,
I had to reinstall the integration because in the same folder I had that of another person which is no longer maintained.
The integratin worked well before deletion, but once reinstalled, I couldn't reconnect to my Audi account.
Everything is OK, I tested my account on MyAudi. I don't see what could be blocking it.
I removed and reinstalled the integration still unable to connect.
Thank you for your help.

**Diagnostics file**
Where to find the files?

![firefox_2024-04-13_22-00-27](https://github.com/cyr-ius/hass-audiconnect/assets/26297241/01ef0db2-8f44-4166-8b4b-e85501f86aaa)

**Comment by Hoekeren** [comment]
I have the same issue.
Here is my log file:

Denne fejl stammer fra en brugerdefineret integration.

Logger: audiconnectpy.auth
Kilde: custom_components/audiconnect/config_flow.py:76
integration: Audi Connect (dokumentation, problemer)
Første forekomst: 08.12.17 (3 forekomster)
Senest logget: 08.12.39

Login to Audi service failed, trying again in 10 seconds [ERROR:Error occurred while communicating with Audi Connect.]
Login to Audi service failed: Error occurred while communicating with Audi Connect.

**Comment by titis14** [comment]
Following the last update for me this was corrected.

**Comment by Hoekeren** [comment]
Log in is now possible. But still not able to lock/unlock doors or anything else. Lots of sensors, but nothing else.

**Comment by tieskuh** [comment]
> Log in is now possible. But still not able to lock/unlock doors or anything else. Lots of sensors, but nothing else.

Locking and unlocking works fine for me. Check the API levels, you might need to change them. See documentation.
