### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by JamieP83** [Cyr-ius/hass-audiconnect#8]
Hey
i seem unable to connect?
<img width="192" alt="image" src="https://user-images.githubusercontent.com/48566948/224139757-09e8bcea-86c9-4eb1-812d-47ad386e5697.png">

im also getting a screen for the setup which looks different to before?
not sure why its not showing in English too, which is my browser language?

<img width="195" alt="image" src="https://user-images.githubusercontent.com/48566948/224139845-4369e206-6f0e-485b-9c5c-da1e1fdbe2a9.png">

**Comment by beardboy69** [comment]
I'm having the exact same issue here.

Oddly if i restart HA, the login prompt is sometimes in English, but other times in French. Bizarre.

Any help appreciated!

**Comment by Cyr-ius** [comment]
> Hey i seem unable to connect? <img alt="image" width="192" src="https://user-images.githubusercontent.com/48566948/224139757-09e8bcea-86c9-4eb1-812d-47ad386e5697.png">
> 
> im also getting a screen for the setup which looks different to before? not sure why its not showing in English too, which is my browser language?
> 
> <img alt="image" width="195" src="https://user-images.githubusercontent.com/48566948/224139845-4369e206-6f0e-485b-9c5c-da1e1fdbe2a9.png">

Please test new version 1.04

**Comment by beardboy69** [comment]
> > Hey i seem unable to connect? <img alt="image" width="192" src="https://user-images.githubusercontent.com/48566948/224139757-09e8bcea-86c9-4eb1-812d-47ad386e5697.png">
> > im also getting a screen for the setup which looks different to before? not sure why its not showing in English too, which is my browser language?
> > <img alt="image" width="195" src="https://user-images.githubusercontent.com/48566948/224139845-4369e206-6f0e-485b-9c5c-da1e1fdbe2a9.png">
> 
> Please test new version 1.04

I have updated to 1.04 but unfortunately getting the same error message as before.

Logger: custom_components.audiconnect.audiconnectpy.auth
Source: custom_components/audiconnect/audiconnectpy/auth.py:195
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 14:35:16 (6 occurrences)
Last logged: 15:08:56

Login to Audi service failed, trying again in 10 seconds
Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=230bc186893672a6f3abb5f9268e31c757f34740&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=584c5e63b9389fa2afe281a9650cf2f13f8658ec&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=2dd756726aacdb7e300549d8092374d3e1a60e7c&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled

**Comment by mm98** [comment]
I don't know if this helps any of you ...

I had `/arjenvrh/audi_connect_ha` and `/Cyr-ius/hass-audiconnect` installed at the same time in `HACS`. Both use the same folder in the filesystem. Meaning if you update or redownload one of them, it would overwrite the other one. Could you please validate, that you only have  `/Cyr-ius/hass-audiconnect` installed in HACS?

**Comment by mm98** [comment]
> Login to Audi service failed, trying again in 10 seconds Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=230bc186893672a6f3abb5f9268e31c757f34740&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=584c5e63b9389fa2afe281a9650cf2f13f8658ec&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=2dd756726aacdb7e300549d8092374d3e1a60e7c&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled

The error your seeing is not from this repo. This errors occues, because your using `/arjenvrh/audi_connect_ha` and not this repo.

This error message shows `09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com` which only exists in [/arjenvrh/audi_connect_ha](https://github.com/arjenvrh/audi_connect_ha/search?q=apps.vw.dilab.com&type=code)

**Comment by mm98** [comment]
You'll have to add this repo as a custom repository in HACS. Remove any existing Audi Connect integration.

**Comment by beardboy69** [comment]
I have done this already, but have just removed this integration from HACS and checked through the File Explorer that it's been removed again, which it has.

I've re-added it and tried signing in again and am still getting the same error.

**Comment by mm98** [comment]
Exact the same error. It is using the wrong URL and I think your still using the wrong repository.

```
Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=584c5e63b9389fa2afe281a9650cf2f13f8658ec&nextButtonDisabled=true&
```

This tires to connect with this part: `apps_vw-dilab_com` which is not valid anymore. It has been removed in Cyr-ius's fix. Which is the reason I think, that your still using `arjenvrh`'s repo.

**Comment by mm98** [comment]
Which repo username does it show, when you click on the `Audi Connect` integration in HACS? .. Does it show `@cyr-ius` or `@arjenvrh` in the upper left corner? .. It should be like this:

![image](https://user-images.githubusercontent.com/992714/225360435-8c733c76-8d4f-4359-9df8-943fb63d7deb.png)

**Comment by beardboy69** [comment]
<img width="618" alt="Screenshot 2023-03-15 at 17 09 18" src="https://user-images.githubusercontent.com/89801408/225387148-01d9d0a9-015c-4e4d-88be-a4a07ad3a04d.png">

It shows the same as yours, so not sure what's going on as i've removed the install, added it again and it all appears to be correct.

**Comment by JamieP83** [comment]
Hey
just applied hte latest update and still getting the same issues

![image](https://user-images.githubusercontent.com/48566948/225883959-468ae64f-15f4-4bb4-8d1f-628d9fe374ee.png)

**Comment by Cyr-ius** [comment]
Please enable debug mode

logger:
  logs:
    custom_components.audiconnect: debug
    audiconnectpy: debug

**Comment by beardboy69** [comment]
I have enabled Debug Mode in my configuration.yaml file.

**Comment by beardboy69** [comment]
This is the latest error:

Logger: custom_components.audiconnect.config_flow
Source: custom_components/audiconnect/audiconnectpy/auth.py:297
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 17:35:11 (1 occurrences)
Last logged: 17:35:11

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/config_flow.py", line 54, in async_step_user
    if await connection.async_login() is False:
  File "/config/custom_components/audiconnect/audiconnectpy/api.py", line 56, in async_login
    self.is_connected = await self._auth.async_connect(
  File "/config/custom_components/audiconnect/audiconnectpy/auth.py", line 187, in async_connect
    await self._async_login(username, password)
  File "/config/custom_components/audiconnect/audiconnectpy/auth.py", line 297, in _async_login
    pw_rsp.headers["Location"],
KeyError: 'Location'

**Comment by Cyr-ius** [comment]
Indeed, in the absence of a response from the Audi API, my code had a defect. I just fixed it in version 1.0.5
Knowing that sometimes, when adding the addon, the site may not respond.
Please try version 1.0.5

**Comment by beardboy69** [comment]
Thanks - unfortunately, still getting errors as below using 1.0.5;

Logger: custom_components.audiconnect.audiconnectpy.auth
Source: custom_components/audiconnect/audiconnectpy/auth.py:200
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 11:46:59 (3 occurrences)
Last logged: 15:24:27

Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=043027da6145052e109414c0ec6c9d5135587412&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=a6fe144a4d0b75241a70d3cfe319960ba474b9cc&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=e93c7c79ba1d3bc66482ad1ca437f7a759044e4c&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled

**Comment by beardboy69** [comment]
<img width="521" alt="Screenshot 2023-03-19 at 12 04 04" src="https://user-images.githubusercontent.com/89801408/226173900-40cac671-500a-4245-956d-4f9eb309497a.png">

My configuration.yaml has the lines added as per the screenshot, so should be working.

I'll look at the logs and see if anything else shows.

**Comment by beardboy69** [comment]
Just tried again and getting a different error;

Logger: custom_components.audiconnect.audiconnectpy.auth
Source: custom_components/audiconnect/audiconnectpy/auth.py:200
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 12:10:39 (1 occurrences)
Last logged: 12:10:39

Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=db18bad55ed4a60f9bc8231dc4c6cb253c2edb52&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled

Can't see any further debug logs though, oddly.

**Comment by Cyr-ius** [comment]
> Just tried again and getting a different error;
> 
> Logger: custom_components.audiconnect.audiconnectpy.auth Source: custom_components/audiconnect/audiconnectpy/auth.py:200 Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues)) First occurred: 12:10:39 (1 occurrences) Last logged: 12:10:39
> 
> Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=db18bad55ed4a60f9bc8231dc4c6cb253c2edb52&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
> 
> Can't see any further debug logs though, oddly.

If you enable beta versions in HACS, you can try version 1.0.6, I redesigned the login related code

**Comment by beardboy69** [comment]
> > Just tried again and getting a different error;
> > Logger: custom_components.audiconnect.audiconnectpy.auth Source: custom_components/audiconnect/audiconnectpy/auth.py:200 Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues)) First occurred: 12:10:39 (1 occurrences) Last logged: 12:10:39
> > Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=db18bad55ed4a60f9bc8231dc4c6cb253c2edb52&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
> > Can't see any further debug logs though, oddly.
> 
> If you enable beta versions in HACS, you can try version 1.0.6, I redesigned the login related code

Thanks - downloaded 1.0.6 Beta to try and restarted HACS.

Could not connect still with the below;

Logger: custom_components.audiconnect.audiconnectpy.auth
Source: custom_components/audiconnect/audiconnectpy/auth.py:191
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 13:19:17 (1 occurrences)
Last logged: 13:19:17

Login to Audi service failed: Error occurred while communicating with Audit Connect.

**Comment by Cyr-ius** [comment]
If you have activated the debug, by clicking on the button "Load Full Log"
![image](https://user-images.githubusercontent.com/1258123/226180117-755c0e70-b10c-4f8b-9421-260e0839e6d5.png)
You should debug traces
![image](https://user-images.githubusercontent.com/1258123/226179821-0713dc83-d0ee-46f2-89bb-7f41e38d45d1.png)

**Comment by beardboy69** [comment]
Here are some of the Debug Logs:

2023-03-19 14:14:32.211 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] Client id: 09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com
2023-03-19 14:14:32.211 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] Audi Base Url: https://emea.bff.cariad.digital/login/v1/audi
2023-03-19 14:14:32.211 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] MBB Base Url: https://mbboauth-1d.prd.ece.vwg-connect.com/mbbcoauth
2023-03-19 14:14:32.211 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] IDK Base Url: https://emea.bff.cariad.digital/login/v1/idk/openid-configuration

2023-03-19 14:14:32.423 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] AuthEndpoint: https://identity.vwgroup.io/oidc/v1/authorize
2023-03-19 14:14:32.423 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] TokenEndpoint: https://emea.bff.cariad.digital/login/v1/idk/token
2023-03-19 14:14:32.423 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] RevocationEndpoint: https://emea.bff.cariad.digital/login/v1/idk/revoke

2023-03-19 14:14:33.303 DEBUG (MainThread) [custom_components.audiconnect.audiconnectpy.auth] HTTP Request error (/signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=9e1d0487de6e848e51538a1c743063eeb2a8d289&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled) (None): /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=9e1d0487de6e848e51538a1c743063eeb2a8d289&nextButtonDisabled=true&enableNextButtonAfterSeconds=3600&error=login.error.throttled
2023-03-19 14:14:33.303 ERROR (MainThread) [custom_components.audiconnect.audiconnectpy.auth] Login to Audi service failed: Error occurred while communicating with Audit Connect.

2023-03-19 14:14:39.404 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140188033363792] Sending {"id":98,"type":"result","success":true,"result":[{"name":"custom_components.audiconnect.audiconnectpy.auth","message":["Login to Audi service failed: Error occurred while communicating with Audit Connect. "],"level":"ERROR","source":["custom_components/audiconnect/audiconnectpy/auth.py",196],"timestamp":1679235273.3036675,"exception":"","count":1,"first_occurred":1679235273.3036675}]}

**Comment by Cyr-ius** [comment]
With version 1.0.6.1, I increased the verbosity of the debug log. So, you can try the connection and send me the debug log

**Comment by JamieP83** [comment]
hey
which "pin" should this be?
is it the one from the audi app itself under "vehjicel connection" / "myAudiPin" ?

also, i presume i use "United Kingdom" for my region, or not? i remember the other app being "EU" i think?

either way, using myAudiPin and UK, it wont connect still :/

<img width="199" alt="image" src="https://user-images.githubusercontent.com/48566948/228914799-bf4c6f13-ae6d-4699-a333-9d668a8947a5.png">

**Comment by Cyr-ius** [comment]
MyAudiPin , the beta version 1.6.0.1 is more verbose. Please enable debug and post log

**Comment by JamieP83** [comment]
working fine now - thank you
i did a password reset via Audi (set the same one again) and all the issues have now gone :)
